export enum TypeTransfert {
    'REGLEMENT PARTIEL FACTURE D\'ACHAT',
    'REGLEMENT DE L\'INTEGRITE D\'UNE FACTURE AVANT LIVRAISON DES MARCHANDISES',
    'REGLEMENT DE L\'INTEGRITE D\'UNE FACTURE  D\'ACHAT DE MARCHANDISES DEJA LIVREES',
    'REGLEMENT D\'UNE FACTURE DE PRESTATION DE SERVICES',
    'REGLEMENT DE FACTURES  D\'ASSISTANCE TECHNIQUE',
    'TRANSFERT POUR LE REMBOURSEMENT D\'UN EMPRUNT',
    'REGLEMENT DE DIVIDENDES A L\'ETRANGER',
}
